<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Ex1_2026_solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@markdown Nome completo e RA (*\<nome\>, \<RA\>*)
Aluno = 'Adriana Fujita, 1115665' #@param {type:"string"}

# **CASE: NFL, National Football League**

Este conjunto de dados apresenta estatísticas de ofensivas da NFL para jogos realizados de 2019 a 2022. São dados como jardas de passe, jardas de corrida, jardas de recepção, etc. dos jogos, estádios etc. Antes de iniciar procure entender como os dados estão organizados os dados.

<br>
<br>

Você poderá achar útil empregar o comando [drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html),

```
df_nodup = df.drop_duplicates()
```

Para excluir dados em uma seleção de dados duplicados. Você pode querer utilizar isso para selecionar somente dados de jogos ou dos estádios. Dados sobre vencedores das partidas podem ser obtidos pela pontuação (`scores`) nos jogos.

In [2]:
import pandas as pd
import numpy as np
path = 'https://github.com/Rogerio-mack/IMT_CD_2026/raw/refs/heads/main/data/'

In [3]:
df = pd.read_csv(path + 'nfl_offensive_stats.csv')
df.head()

,game_id,player_id,position,player,team,pass_cmp,pass_att,pass_yds,pass_td,pass_int,...,OT,Roof,Surface,Temperature,Humidity,Wind_Speed,Vegas_Line,Vegas_Favorite,Over_Under,game_date
0,201909050chi,RodgAa00,QB,Aaron Rodgers,GNB,18,30,203,1,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,9/5/2019
1,201909050chi,JoneAa00,RB,Aaron Jones,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,9/5/2019
2,201909050chi,ValdMa00,WR,Marquez Valdes-Scantling,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,9/5/2019
3,201909050chi,AdamDa01,WR,Davante Adams,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,9/5/2019
4,201909050chi,GrahJi00,TE,Jimmy Graham,GNB,0,0,0,0,0,...,False,outdoors,grass,65,69,10,-3.5,CHI,47.0,9/5/2019

# Q1.

(NFL) Qual a média de passes completos (`pass_cmp`) do jogador 'Aaron Rodgers' nos jogos que se encontram na base?

In [4]:
df[ df.player == 'Aaron Rodgers'].pass_cmp.mean()

np.float64(22.90566037735849)

In [5]:
pass_cmp_mean_Aaron = df[ df.player == 'Aaron Rodgers'].pass_cmp.mean()

print(pass_cmp_mean_Aaron)

22.90566037735849

# Q2.

(NFL) Por quantos times diferentes jogaram 'Phillip Dorsett' e 'Marcus Johnson' no período de jogos que se encontram na base?

In [6]:
display(df[ (df.player == 'Phillip Dorsett') ].team.unique())
display(df[ (df.player == 'Phillip Dorsett') ].team.nunique())

display(df[ (df.player == 'Marcus Johnson') ].team.unique())
display(df[ (df.player == 'Marcus Johnson') ].team.nunique())

array(['NWE', 'JAX', 'SEA', 'HOU'], dtype=object)

4

array(['IND', 'TEN'], dtype=object)

2

In [7]:
Phillip_Dorsett = len(df[ (df.player == 'Phillip Dorsett') ].team.unique())
Marcus_Johnson = len(df[ (df.player == 'Marcus Johnson') ].team.unique())

print(Phillip_Dorsett, Marcus_Johnson)

4 2

# Q3.

(NFL) Quantos jogos estão representados na base?

In [8]:
df.game_id.nunique()

820

In [9]:
len(df.game_id.drop_duplicates())

820

In [10]:
num_games = df.game_id.nunique()

print(num_games)

820

# Q4.

(NFL) O "Bufalo Bulls" (`BUF`) participou de quantos jogos dentre os jogos na base?

Para isso pode ser interessante criar uma base de jogos. O "Bufalo Bulls" pode ter jogado em casa ou como visitante.

In [11]:
df_games = df[['game_id', 'home_team','home_score','vis_team','vis_score']].drop_duplicates()
df_games.head()

         game_id home_team  home_score vis_team  vis_score
0   201909050chi       CHI           3      GNB         10
24  201909080car       CAR          27      LAR         30
44  201909080cle       CLE          13      TEN         43
68  201909080crd       ARI          27      DET         27
91  201909080dal       DAL          35      NYG         17

In [12]:
len( df_games[ (df_games.home_team == 'BUF') | (df_games.vis_team == 'BUF') ] )

55

In [13]:
num_games_BUF = len( df_games[ (df_games.home_team == 'BUF') | (df_games.vis_team == 'BUF') ] )

print(num_games_BUF)

55

# Q5.
(NFL) Qual time fez mais jogos em casa considerando os jogos da base?

In [14]:
df_games.home_team.value_counts().head()

home_team
KAN    33
GNB    28
BUF    28
NOR    27
CIN    27
Name: count, dtype: int64

In [15]:
top_games_team = df_games.home_team.value_counts().head(1).index[0]

print(top_games_team)

KAN

# Q6.
Qual foi o percentual de partidas ganhas pelo "Bufalo Bulls" considerados todos os jogos da base em que participou?

In [16]:
home = (df_games.home_team == 'BUF')
visit = (df_games.vis_team == 'BUF')

( sum(df_games[ home ].home_score - df_games[ home ].vis_score > 0) + sum(df_games[ visit ].vis_score - df_games[ visit ].home_score > 0) ) / len( df_games[ (df_games.home_team == 'BUF') | (df_games.vis_team == 'BUF') ] )

0.6727272727272727

In [17]:
percent_BUF = 100*( sum(df_games[ home ].home_score - df_games[ home ].vis_score > 0) + sum( df_games[ visit ].vis_score - df_games[ visit ].home_score > 0) ) / len( df_games[ (df_games.home_team == 'BUF') | (df_games.vis_team == 'BUF') ] )

print(percent_BUF)

67.27272727272727

# Q7.
(NFL) Que tipo de Superfície nos estádios não são encontradas nos estádios com teto (`Roof`) do tipo `outdoors`?

In [18]:
df_games = df[['Roof','Surface']].drop_duplicates()

list_types = list( set(df_games.Surface.unique()) - set(df_games[df_games.Roof == 'outdoors'].Surface.unique()) )

print(list_types)

['sportturf', 'matrixturf']

In [19]:
list_types = list( set(df_games.Surface.unique()) - set(df_games[df_games.Roof == 'outdoors'].Surface.unique()) )

print(list_types)

['sportturf', 'matrixturf']

# Q8.
(NFL) Você pode afirmar, com base nos jogos da base, que os resultados dos jogos (vitórias) favorecem o time "da casa"?

In [20]:
df_games = df[['game_id','home_team','home_score','vis_team','vis_score']].drop_duplicates()
df_games.head()

         game_id home_team  home_score vis_team  vis_score
0   201909050chi       CHI           3      GNB         10
24  201909080car       CAR          27      LAR         30
44  201909080cle       CLE          13      TEN         43
68  201909080crd       ARI          27      DET         27
91  201909080dal       DAL          35      NYG         17

In [21]:
sum( df_games.home_score > df_games.vis_score ) / len(df_games)

0.5097560975609756

A diferença é muito pequena e não dá para afirmar que jogos em casa favorecem o placar para os times da casa.

Você ainda não aprendeu isso (veremos isso mais adiante ainda neste semestre), mas uma forma mais rigorosa de verificarmos isso é com o teste de hipótese como abaixo. Mas para o exercício aqui, isso não era necessário.

In [22]:
from scipy import stats

# H0: home_score e vis_score são iguais
# H1: home_score é significativamente maior que vis_score

t_stat, p_value = stats.ttest_ind(df_games.home_score, df_games.vis_score, alternative='greater')

print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

alpha = 0.05

if p_value < alpha:
    print("Rejeitamos a hipótese nula. home_score é significativamente maior que vis_score.")
else:
    print("Falhamos em rejeitar a hipótese nula. Não há evidência suficiente para afirmar que home_score é significativamente maior que vis_score.")

T-statistic: 1.3491956573861659
P-value: 0.08873029643487931
Falhamos em rejeitar a hipótese nula. Não há evidência suficiente para afirmar que home_score é significativamente maior que vis_score.

# **CASE: Gapminder**

Esta é uma base de dados com dados do consumo de barris de petróleo no mundo a partir dos anos 2000.

In [23]:
df = pd.read_csv(path + 'oil_consumption_barrels.csv')
df

                      geo  year  oil_consumption_barrels
0                  canada  2000               2062.66692
1                  mexico  2000               2045.78980
2           united_states  2000              19593.51897
3     total_north_america  2000              23701.97569
4               argentina  2000                483.65601
...                   ...   ...                      ...
2569            argentina  2024                604.33533
2570  total_north_america  2024              23181.50734
2571        united_states  2024              18995.00546
2572               mexico  2024               1853.30290
2573               canada  2024               2333.19898

[2574 rows x 3 columns]

# Q9.

Qual a média de consumo do Brasil considerando todos os anos?

In [27]:
mean_brasil = df[ (df.geo == 'brazil') & (df.year != 'all') ].oil_consumption_barrels.mean()

print(mean_brasil)

2315.9795520000002

# Q10.

Quais são os 5 top países consumidores de barris de petróleo no ano de 2024?

In [ ]:
df_top5 = df[ (df.year == '2024') & ~(df.geo.isin(set([ geo for geo in df.geo if geo.startswith('total_') ]) )) ].nlargest(10, 'oil_consumption_barrels').head(5)

df_top5

                     geo  year  oil_consumption_barrels
2571       united_states  2024              18995.00546
2492               china  2024              16373.50818
2490               india  2024               5620.53699
2508        saudi_arabia  2024               3958.60081
2519  russian_federation  2024               3846.33342

In [ ]:
top5_oil_consumption_barrels = df_top5.geo.tolist()

print(top5_oil_consumption_barrels)

['united_states', 'china', 'india', 'saudi_arabia', 'russian_federation']

# Q11.

Qual o percentual do consumo dos 5 top países consumidores de barris de petróleo no ano de 2024 com relação ao total de consumo no mundo no ano de 2024?

In [ ]:
perc_top5 = 100 * df[ (df.year == '2024') & (df.geo.isin(top5_oil_consumption_barrels)) ].oil_consumption_barrels.sum() / df[ (df.year == '2024') & (df.geo == 'total_world')].oil_consumption_barrels.sum()

print(perc_top5)

48.111765433909596

# **CASE: European Energy**

Os dados abaixo são da matroz energética da UE. Após entender os dados, crie os scripts necessários para responder as seguintes perguntas.

In [ ]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/refs/heads/main/data/energy.csv')
df.head()

,country,country_name,type,level,2016,2017,2018
0,BE,Belgium,Conventional thermal,Level 1,30728.0,31316.0,30092.635
1,BE,Belgium,Nuclear,Level 1,41430.0,40128.5,26995.628
2,BE,Belgium,Hydro,Level 1,1476.0,1360.9,1239.248
3,BE,Belgium,Pumped hydro power,Level 2,1110.0,1093.2,983.190
4,BE,Belgium,Wind,Level 1,5340.0,6387.9,7177.346

# Q12.

(European Energy) Quantos países há na base?

In [ ]:
df.country_name.nunique(),

(37, 37)

In [ ]:
nr_countries = df.country_name.nunique()

print(nr_countries)

37

# Q13.

(European Energy) Qual percentual de energia nuclear produzida na Europa no ano de 2018?

In [ ]:
perc_energy = df[df.type == 'Nuclear']['2018'].sum() / df['2018'].sum() * 100

print(perc_energy)

22.92525276913767

# Q14.

(European Energy) Qual o percentual da energia da França que vem de energia nuclear no ano de 2018?

In [ ]:
perc_FR = df[(df.type == 'Nuclear') & (df.country_name == 'France')]['2018'].sum() / df[ df.country_name == 'France' ]['2018'].sum() * 100

print(perc_FR)

70.10980377654339

# **CASE: Ações B3 NYC**

A base de dados a seguir traz valores de fechamento, % de valorização diária (%) e volume negociado (V) de vários ativos de 2019 a 2025.

  - `BVSP`, Índice Bovespa
  - `PETR4.SA`,
  - `VALE3.SA`,
  - `BRL=X`, Cotação do Dólar
  - `ITUB3.SA`,
  - `BTC-USD`, BitCoin US

Valores monetários são em moeda corrente. Valores ausentes indicam ausência de pregão/cotação, mas não há necessidade de qualquer tratamento aqui. Após entender os dados, crie os scripts necessários para responder as seguintes perguntas.

In [ ]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/refs/heads/main/data/stocks_2019_2025.csv')
df.head()

,Date,BRL=X,BTC-USD,ITUB3.SA,PETR4.SA,VALE3.SA,^BVSP,BRL=X %,BTC-USD %,ITUB3.SA %,PETR4.SA %,VALE3.SA %,^BVSP %,BRL=X V,BTC-USD V,ITUB3.SA V,PETR4.SA V,VALE3.SA V,^BVSP V
0,2019-01-01,3.8800,3843.520020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4324200990,NaN,NaN,NaN,NaN
1,2019-01-02,3.8799,3943.409424,20.093735,7.466959,30.699385,91012.0,-0.000026,0.025989,NaN,NaN,NaN,NaN,0.0,5244856836,1074590.0,104534800.0,17319600.0,5615400.0
2,2019-01-03,3.7863,3836.741211,20.276070,7.650064,29.443529,91564.0,-0.024124,-0.027050,0.009074,0.024522,-0.040908,0.006065,0.0,4530215219,311300.0,95206400.0,30120000.0,6066200.0
3,2019-01-04,3.7551,3857.717529,19.936563,7.671789,31.360359,91841.0,-0.008240,0.005467,-0.016744,0.002840,0.065102,0.003025,0.0,4847965467,370040.0,72119800.0,43360100.0,5322100.0
4,2019-01-05,NaN,3845.194580,NaN,NaN,NaN,NaN,0.000000,-0.003246,0.000000,0.000000,0.000000,0.000000,NaN,5137609824,NaN,NaN,NaN,NaN

# Q14.

Considerando todo o período, qual a valorização dos ativos de maior e menor ganho percentual?

> **Aqui empregamos o ganho acumulado linearizado, uma medida/índice mais simples e comum para avaliar taxas (como ações ou a inflação (IPCA)).**

In [ ]:
df_ganhos = df[['BRL=X %', 'BTC-USD %', 'ITUB3.SA %', 'PETR4.SA %', 'VALE3.SA %', '^BVSP %']].sum().sort_values(ascending=False)

In [ ]:
ganho_max = df_ganhos.max() * 100
ganho_min = df_ganhos.min() * 100

print(ganho_min, ganho_max)

46.51262500398822 437.5946032567592

# Q15.
Uma métrica comum na avaliação de ativos é verificarmos, em um período, a quantidade de dias em que o ativo teve valorização com relação ao dia anterior (**up and down**). Considerando todo o período, qual o percentual de `ups` dos ativos com mais e menos `ups`.

Gere uma lista do maior para o menor.

In [ ]:
df_up_downs = (df[['BRL=X %', 'BTC-USD %', 'ITUB3.SA %', 'PETR4.SA %', 'VALE3.SA %', '^BVSP %']] > 0).sum() / len(df) * 100

In [ ]:
df_up_downs.sort_values(ascending=False).values

array([51.21198766, 36.27148524, 35.47818422, 35.08153372, 33.6712208 ,
       33.2745703 ])

In [ ]:
top_up_downs = df_up_downs.sort_values(ascending=False).index.tolist()

print(top_up_downs)

['BTC-USD %', 'BRL=X %', 'PETR4.SA %', '^BVSP %', 'ITUB3.SA %', 'VALE3.SA %']

# Q16.

A *MAIOR PARTE* dos ativos da base teve sua maior valorização em um único dia no mesmo ano e mês. Qual foi esse ano-mês especial?

In [ ]:
for c in ['BRL=X %', 'BTC-USD %', 'ITUB3.SA %', 'PETR4.SA %', 'VALE3.SA %', '^BVSP %']:
  print(df.nlargest(2,c)[['Date',c]])

           Date   BRL=X %
497  2020-05-12  0.062096
541  2020-06-25  0.037973
           Date  BTC-USD %
769  2021-02-08   0.187465
443  2020-03-19   0.181878
           Date  ITUB3.SA %
437  2020-03-13    0.110330
483  2020-04-28    0.084419
           Date  PETR4.SA %
437  2020-03-13    0.222222
448  2020-03-24    0.152174
           Date  VALE3.SA %
437  2020-03-13    0.213579
434  2020-03-10    0.184509
           Date   ^BVSP %
437  2020-03-13  0.139082
448  2020-03-24  0.096885