<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Ex_groupby_solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

In [ ]:
import pandas as pd
import numpy as np

## **CASE Tips**

# Q1.

Considere a base de dados [`tips`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/tips.csv). Considerando somente os finais de semana, quem tem média de participantes na mesa maior, fumantes ou não fumantes? **`[NoGroup | GroupBy]`**

In [ ]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/main/data/tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Não é necessário fazer assim...

In [ ]:
print('Não fumantes tem média de participantes na mesa maior que fumantes? ',
      df[ (df.smoker == 'Yes') & (df.day.isin(['Sat','Sun'])) ]['size'].mean() <
      df[ (df.smoker == 'No') & (df.day.isin(['Sat','Sun'])) ]['size'].mean())

Não fumantes tem média de participantes na mesa maior que fumantes?  True

Assim, é suficientemente bom...

In [ ]:
df[ (df.smoker == 'Yes') & (df.day.isin(['Sat','Sun'])) ]['size'].mean()

np.float64(2.5081967213114753)

In [ ]:
df[ (df.smoker == 'No') & (df.day.isin(['Sat','Sun'])) ]['size'].mean()

np.float64(2.764705882352941)

Usando `groupby()`...

In [ ]:
df[ df.day.isin(['Sat','Sun']) ].groupby('smoker')['size'].mean()

smoker
No     2.764706
Yes    2.508197
Name: size, dtype: float64

## **CASE Insurance**

Acesse a base de dados [`insurance`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/insurance.csv) para as questões a seguir.

In [ ]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/main/data/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Q2.

Qual percentual de homens e mulheres assegurados na base? **`[NoGroup | GroupBy]`**

In [ ]:
fem = len( df[df.sex == 'female'] ) / len(df)
print(f'Percentual de Mulheres seguradas: {fem:.4f}')

masc = len( df[df.sex == 'male'] ) / len(df)
print(f'Percentual de Homens segurados: {masc:.4f}')

Percentual de Mulheres seguradas: 0.4948
Percentual de Homens segurados: 0.5052

Usando `groupby()`...

In [ ]:
df.groupby('sex').sex.count() / df.sex.count()

sex
female    0.494768
male      0.505232
Name: sex, dtype: float64

`count()`... Calcula a contagem do grupo, excluindo os valores ausentes...

In [ ]:
df.groupby('sex').sex.count()

sex
female    662
male      676
Name: sex, dtype: int64

In [ ]:
df.loc[0,'sex'] = None

df.groupby('sex').sex.count()

sex
female    661
male      676
Name: sex, dtype: int64

In [ ]:
df.groupby('sex',dropna=False).sex.count()

sex
female    661
male      676
NaN         0
Name: sex, dtype: int64

# Q3.

Qual o total do valor de seguro pago por homens e mulheres segurados na base? **`[NoGroup | GroupBy]`**

In [ ]:
# restor values...

df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/main/data/insurance.csv')

In [ ]:
fem = sum( df[df.sex == 'female'].charges )
print(f'Total dos Seguros (Mulheres):  {fem:.2f}')

masc = sum( df[df.sex == 'male'].charges )
print(f'Total dos Seguros (Homens):  {masc:.2f}')

Total dos Seguros (Mulheres):  8321061.19
Total dos Seguros (Homens):  9434763.80

Usando `groupby()`...

In [ ]:
df.groupby('sex').charges.sum()

sex
female    8.321061e+06
male      9.434764e+06
Name: charges, dtype: float64

In [ ]:
df.groupby('sex').charges.sum().apply(lambda x: '{:.2f}'.format(x))

sex
female    8321061.19
male      9434763.80
Name: charges, dtype: object

# Q4.

Qual o percentual de valor de seguros pagos por homens e mulheres segurados na base? **`[NoGroup | GroupBy]`**

In [ ]:
fem = sum( df[df.sex == 'female'].charges ) / sum( df.charges )
print(f'Total dos Seguros (Mulheres):  {fem:.2f}')

masc = sum( df[df.sex == 'male'].charges ) / sum( df.charges )
print(f'Total dos Seguros (Homens):  {masc:.2f}')

Total dos Seguros (Mulheres):  0.47
Total dos Seguros (Homens):  0.53

Com `groupby()`...

In [ ]:
df.groupby('sex').charges.sum() / df.charges.sum()

sex
female    0.468638
male      0.531362
Name: charges, dtype: float64

# Q5.

Não fumantes apresentam em média mais filhos? **`[NoGroup | GroupBy]`**

In [ ]:
df[df.smoker == 'yes'].children.mean() > df[df.smoker == 'no'].children.mean()

np.True_

Ou...

In [ ]:
df.groupby('smoker').children.mean() >= df.groupby('smoker').children.mean().max()

smoker
no     False
yes     True
Name: children, dtype: bool

# Q6.

Qual a média e maior de idade dentre os segurados homem, das regiões northwest ou northeast? **`[NoGroup | GroupBy]`**

In [ ]:
df[ (df.sex == 'male') & (df.region.isin(['northwest','northeast']) ) ].age.mean()

38.848765432098766

In [ ]:
df[ (df.sex == 'male') & (df.region.isin(['northwest','northeast']) ) ].age.max()

64

Ou...

In [ ]:
df[ df.region.isin(['northwest','northeast']) ].groupby('sex').age.agg(['mean','max'])

             mean  max
sex
female  39.615385   64
male    38.848765   64