<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Ex_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

In [ ]:
import numpy as np
import pandas as pd

# **CASE: Yahoo Finance**

Nos exercícios a seguir partimos da seguinte base de dados extraída do `yahoo finance`:

In [ ]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2025/raw/refs/heads/main/data/stocks_2019_2025.csv')
df = df[['Date', 'BRL=X', 'ITUB3.SA', 'PETR4.SA', 'VALE3.SA', '^BVSP', 'BTC-USD']]
df.head()

         Date   BRL=X   ITUB3.SA  PETR4.SA   VALE3.SA    ^BVSP      BTC-USD
0  2019-01-01  3.8800        NaN       NaN        NaN      NaN  3843.520020
1  2019-01-02  3.8799  20.093735  7.466959  30.699385  91012.0  3943.409424
2  2019-01-03  3.7863  20.276070  7.650064  29.443529  91564.0  3836.741211
3  2019-01-04  3.7551  19.936563  7.671789  31.360359  91841.0  3857.717529
4  2019-01-05     NaN        NaN       NaN        NaN      NaN  3845.194580

# Q1.

Empregue os métodos de reshape do `pandas` e a função `pd.to_datetime(df.Date).dt.day_name()` para transformar o dataframe `df` para o formato abaixo.

             Date   Ticket     Adj Close day_of_week
0      2019-01-01    BRL=X      3.880000     Tuesday
1      2019-01-02    BRL=X      3.879900   Wednesday
2      2019-01-03    BRL=X      3.786300    Thursday
3      2019-01-04    BRL=X      3.755100      Friday
4      2019-01-05    BRL=X           NaN    Saturday
...           ...      ...           ...         ...
13609  2025-03-14  BTC-USD  83969.101562      Friday
13610  2025-03-15  BTC-USD  84343.109375    Saturday
13611  2025-03-16  BTC-USD  82579.687500      Sunday
13612  2025-03-17  BTC-USD  84075.687500      Monday
13613  2025-03-18  BTC-USD  82718.500000     Tuesday

[13614 rows x 4 columns]

In [ ]:
#@markdown Must be True
len(df_melt[ df_melt.day_of_week == 'Tuesday' ]) == 1950

True

Qual o maior valor do Real às sextas-feiras (`Friday`) dentro do período e em que data isso ocorreu? (Atenção, a base contém cotações do dólar).

## Q2.

Empregue os métodos de reshape do `pandas` remodelar o dataframe criado no exercício anterior produzindo o dataframe `df_Friday` que contém somente valores de fechamento da semana (`Friday`) dos ativos como no formato abaixo.

Ticket       BRL=X      BTC-USD   ITUB3.SA  PETR4.SA   VALE3.SA    ^BVSP
Date
2019-01-04  3.7551  3857.717529  19.936563  7.671789  31.360359  91841.0
2019-01-11  3.7079  3687.365479  20.200619  7.755583  31.474533  93658.0
2019-01-18  3.7489  3657.839355  20.307501  7.882824  32.904644  96097.0
2019-01-25  3.7698  3599.765869        NaN       NaN        NaN      NaN
2019-02-01  3.6428  3487.945312  20.568373  8.006965  27.791084  97861.0

In [ ]:
#@markdown Must be True
int(df_Friday['BRL=X'].sum()) == 1630

True

Qual a média da cotação do dólar nas últimas 4 sextas-feiras da base?

# Q3.

Empregue df_melt para obter a data de maior valor de cada um dos ativos.