<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/IMT_CD_EX_32_Classification_CV_exercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Atividade Avaliativa 3.2 - ECM514 Ciência de Dados**

In [ ]:
#@markdown Nome **COMPLETO** e RA

Nome = 'Anna Karenina' #@param {type:"string"}
RA = '22.01164-0' #@param {type:"string"}
#@markdown

suffix_file = RA.replace('.','')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ipywidgets as widgets
from IPython.display import display

path = 'https://github.com/Rogerio-mack/IMT_CD_2026/raw/main/data/'

#@markdown Salve o seu notebook com **IMT_CD_EX_32_\<seu_nome\>.ipynb**

#@markdown Execute esta célula para prosseguir.

# **CASE**: Adult-census

Selecione o melhor modelo de classificação de `class`, entre uma regressão logística e modelos knn (k=3-8). Valores ausentes podem ser imputados seguindo a distribuição por gênero. Para avaliar os modelos empregue uma validação cruzada do modelo com 5 partições. Verifique, além da acuracidade, outras métricas do modelo. Faça a predição de dois sujeitos fictícios com os valores de *features* mais e menos frequentes.

Empregue `seed = 42` para todas as execuções randômicas e 20% de dados de teste estratificados. **Não empregar o `pipeline` scikit-learn que será visto adiante.**

In [1]:
import pandas as pd

df = pd.read_csv("https://github.com/INRIA/scikit-learn-mooc/raw/refs/heads/main/datasets/adult-census.csv")
df.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [5]:
df.value_counts('class')

class
<=50K    37155
>50K     11687
Name: count, dtype: int64

![imagem](https://github.com/Rogerio-mack/IMT_CD_2026/blob/main/pipeline_ex.png?raw=true)

### Perguntas

1. (Preparação dos dados) Informe o formato dos conjuntos de treinamento e teste.
2. (Preparação dos dados) Quantos valores nulos foram tratados?
3. (Preparação dos dados) Informe a média dos valores dos conjuntos de treinamento e teste.
4. (Seleção dos modelos) Informe os 3 melhores modelos e sua acuracidade (CV).
5. (Modelo final) Qual a acuracidade do modelo final no conjunto de teste?
6. (Modelo final) Quais as quantidades de TP e FN do modelo final no conjunto de teste para <=50K?
7. (Predição) Qual a probabilidade das classes <=50K e >50K nos dois casos de predição?